### ISSUE TITLE
Prices today are prices of tomorrow

### ISSUE THREAD

**Issue by ronaldt80** [Roeland54/ha-entso-e#2]
First of all thanks for taking over from the original owner. I installed you version as I had issues with the later versions of the original repo. I seems though some of these have progressed / been inherited in yours.

Earlier today the integration pulled new prices, so far so good. However these are now in the "wrong place"- prices_today contain the prices of tomorrow, prices_tomorrow is empty, prices contains all information (both today and tomorrow). Any thoughts what is causing this? See below the attributes:

```
unit_of_measurement: €/kWh
device_class: monetary
icon: mdi:currency-eur
friendly_name: Average electricity price today
prices_today:
  - time: "2024-08-26 00:00:00+02:00"
    price: 0.2631
  - time: "2024-08-26 01:00:00+02:00"
    price: 0.25034
  - time: "2024-08-26 02:00:00+02:00"
    price: 0.24829
  - time: "2024-08-26 03:00:00+02:00"
    price: 0.24357
  - time: "2024-08-26 04:00:00+02:00"
    price: 0.24726
  - time: "2024-08-26 05:00:00+02:00"
    price: 0.2516
  - time: "2024-08-26 06:00:00+02:00"
    price: 0.28728
  - time: "2024-08-26 07:00:00+02:00"
    price: 0.28359
  - time: "2024-08-26 08:00:00+02:00"
    price: 0.26055
  - time: "2024-08-26 09:00:00+02:00"
    price: 0.23937
  - time: "2024-08-26 10:00:00+02:00"
    price: 0.19037
  - time: "2024-08-26 11:00:00+02:00"
    price: 0.16784
  - time: "2024-08-26 12:00:00+02:00"
    price: 0.1577
  - time: "2024-08-26 13:00:00+02:00"
    price: 0.1577
  - time: "2024-08-26 14:00:00+02:00"
    price: 0.17142
  - time: "2024-08-26 15:00:00+02:00"
    price: 0.18116
  - time: "2024-08-26 16:00:00+02:00"
    price: 0.19792
  - time: "2024-08-26 17:00:00+02:00"
    price: 0.27126
  - time: "2024-08-26 18:00:00+02:00"
    price: 0.2897
  - time: "2024-08-26 19:00:00+02:00"
    price: 0.37671
  - time: "2024-08-26 20:00:00+02:00"
    price: 0.42303
  - time: "2024-08-26 21:00:00+02:00"
    price: 0.32389
  - time: "2024-08-26 22:00:00+02:00"
    price: 0.28596
  - time: "2024-08-26 23:00:00+02:00"
    price: 0.28064
prices_tomorrow: []
prices:
  - time: "2024-08-25 00:00:00+02:00"
    price: 0.15212
  - time: "2024-08-25 01:00:00+02:00"
    price: 0.15276
  - time: "2024-08-25 02:00:00+02:00"
    price: 0.15165
  - time: "2024-08-25 03:00:00+02:00"
    price: 0.15074
  - time: "2024-08-25 04:00:00+02:00"
    price: 0.15096
  - time: "2024-08-25 05:00:00+02:00"
    price: 0.15165
  - time: "2024-08-25 06:00:00+02:00"
    price: 0.15171
  - time: "2024-08-25 07:00:00+02:00"
    price: 0.15164
  - time: "2024-08-25 08:00:00+02:00"
    price: 0.15165
  - time: "2024-08-25 09:00:00+02:00"
    price: 0.14997
  - time: "2024-08-25 10:00:00+02:00"
    price: 0.1443
  - time: "2024-08-25 11:00:00+02:00"
    price: 0.13943
  - time: "2024-08-25 12:00:00+02:00"
    price: 0.13289
  - time: "2024-08-25 13:00:00+02:00"
    price: 0.12821
  - time: "2024-08-25 14:00:00+02:00"
    price: 0.12688
  - time: "2024-08-25 15:00:00+02:00"
    price: 0.13946
  - time: "2024-08-25 16:00:00+02:00"
    price: 0.14518
  - time: "2024-08-25 17:00:00+02:00"
    price: 0.14862
  - time: "2024-08-25 18:00:00+02:00"
    price: 0.22328
  - time: "2024-08-25 19:00:00+02:00"
    price: 0.28064
  - time: "2024-08-25 20:00:00+02:00"
    price: 0.29955
  - time: "2024-08-25 21:00:00+02:00"
    price: 0.28223
  - time: "2024-08-25 22:00:00+02:00"
    price: 0.27392
  - time: "2024-08-25 23:00:00+02:00"
    price: 0.26356
  - time: "2024-08-26 00:00:00+02:00"
    price: 0.2631
  - time: "2024-08-26 01:00:00+02:00"
    price: 0.25034
  - time: "2024-08-26 02:00:00+02:00"
    price: 0.24829
  - time: "2024-08-26 03:00:00+02:00"
    price: 0.24357
  - time: "2024-08-26 04:00:00+02:00"
    price: 0.24726
  - time: "2024-08-26 05:00:00+02:00"
    price: 0.2516
  - time: "2024-08-26 06:00:00+02:00"
    price: 0.28728
  - time: "2024-08-26 07:00:00+02:00"
    price: 0.28359
  - time: "2024-08-26 08:00:00+02:00"
    price: 0.26055
  - time: "2024-08-26 09:00:00+02:00"
    price: 0.23937
  - time: "2024-08-26 10:00:00+02:00"
    price: 0.19037
  - time: "2024-08-26 11:00:00+02:00"
    price: 0.16784
  - time: "2024-08-26 12:00:00+02:00"
    price: 0.1577
  - time: "2024-08-26 13:00:00+02:00"
    price: 0.1577
  - time: "2024-08-26 14:00:00+02:00"
    price: 0.17142
  - time: "2024-08-26 15:00:00+02:00"
    price: 0.18116
  - time: "2024-08-26 16:00:00+02:00"
    price: 0.19792
  - time: "2024-08-26 17:00:00+02:00"
    price: 0.27126
  - time: "2024-08-26 18:00:00+02:00"
    price: 0.2897
  - time: "2024-08-26 19:00:00+02:00"
    price: 0.37671
  - time: "2024-08-26 20:00:00+02:00"
    price: 0.42303
  - time: "2024-08-26 21:00:00+02:00"
    price: 0.32389
  - time: "2024-08-26 22:00:00+02:00"
    price: 0.28596
  - time: "2024-08-26 23:00:00+02:00"
    price: 0.28064
```
